import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Providers } from '@/lib/providers';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'; // or `v14-appRouter` if you are using Next.js v14
import ThemeRegistry from '@/theme/ThemeRegistry';

// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/* 
TO DRILL THEME :  https://blog.logrocket.com/getting-started-mui-next-js/`
<ThemeRegistry options={{ key: 'mui-theme' }}>{children}</ThemeRegistry>
              or 
{/* <AppRouterCacheProvider>{children}</AppRouterCacheProvider> } 

*/

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <Providers>
      <html lang="en">
        <body>
          <ThemeRegistry options={{ key: 'mui-theme' }}>{children}</ThemeRegistry>
        </body>
      </html>
    </Providers>
  );
}
