import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Providers } from '@/lib/providers';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'; // or `v14-appRouter` if you are using Next.js v14
// import ThemeRegistry from '@/theme/ThemeRegistry';
import { SettingsProvider } from '@/context/settingsContext';
import ThemeComponent from '@/theme/ThemeComponent';

// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <Providers>
      <html lang="en">
        <body>
          <SettingsProvider>{children}</SettingsProvider>
        </body>
      </html>
    </Providers>
  );
}
